name: Deploy frontend to S3

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: terraform-frontend-75c82096

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1

      - name: Uploads site to S3
        run: aws s3 sync . s3://${{ env.S3_BUCKET }}/ --delete
